language: generic
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: jyasskin+travisci@google.com
before_install:
- openssl aes-256-cbc -K $encrypted_1b3d4239d007_key -iv $encrypted_1b3d4239d007_iv
  -in deploy_key.enc -out deploy_key -d
